**Python DA Assignment 1: Data Analysis using**
**NumPy and Pandas **

Numpy Array Operations:
Problem Statement: To learn how to use NumPy for creating arrays, performing basic
array operations, and conducting numerical computations through analyzing
temperature data.
Scenario: You are given a list of daily average temperatures (in degrees Celsius)
recorded over two weeks. Your task is to use NumPy to analyze this data.

1. Create a 1D NumPy Array:
Create a 1D NumPy array named temperatures_w1 for Week 1 with the
following values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [2]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

print(temperatures_w1.ndim)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
1


2. Inspection and Properties:
● Inspect the shape, data type, and the number of elements in the array.
Inspect the shape of the temperatures_w1 array.

In [3]:
print(temperatures_w1.shape)

(7,)


3. Array Operations:
● Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32
● Find the maximum, minimum, and mean temperatures for the week.

In [5]:
fahrenheit_w1 = (temperatures_w1 * 9/5) + 32

print("Temperatures in Fahrenheit:")
print(fahrenheit_w1)

print("Maximum temperature:", np.max(temperatures_w1))
print("Minimum temperature:", np.min(temperatures_w1))
print("Mean temperature:", np.mean(temperatures_w1))

Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum temperature: 26.1
Minimum temperature: 20.8
Mean temperature: 23.542857142857144


4. Array Slicing and Indexing:
● Extract the temperatures for the first three days of the week.
● Extract the temperatures for the weekend (last two days).
● Extract the temperatures for the middle three days of the week.

In [6]:
# First three days
first_three_days = temperatures_w1[0:3]
print("First three days:", first_three_days)

# Weekend (last two days)
weekend = temperatures_w1[-2:]
print("Weekend temperatures:", weekend)

# Middle three days
middle_three_days = temperatures_w1[2:5]
print("Middle three days:", middle_three_days)

First three days: [22.5 25.3 20.8]
Weekend temperatures: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]


5. Create a 2D Array:
Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:
★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [7]:
import numpy as np

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


6. Inspect and Slice the 2D Array:
● Inspect and print the shape, data type, and total number of elements in the
temperatures array.
● Extract the temperatures for each week and the weekends (last two days)
for both weeks.

In [8]:
# Inspect the array
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

# Extract each week
week1 = temperatures[0]
week2 = temperatures[1]

print("Week 1:", week1)
print("Week 2:", week2)

# Extract weekends for both weeks
weekends = temperatures[:, -2:]

print("Weekend temperatures:")
print(weekends)

Shape: (2, 7)
Data type: float64
Total number of elements: 14
Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekend temperatures:
[[24.8 21.9]
 [22.8 20.1]]


**Pandas Series:**
1. Creating Pandas Series:
● Create a Pandas Series named marks with the following data:
➢ Marks: 95, 92, 89, 85, 80
➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [9]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


2. Indexing and Slicing:
● Use the integer index position to access the mark of the 1st rank student.
● Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels.
● Use the iloc accessor to retrieve the mark of the 3rd rank student.
● Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.

In [10]:
# 1. Access 1st rank using integer position
print("1st Rank:", marks[0])

# 2. Retrieve top 3 ranks using loc
print("\nTop 3 Ranks:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

# 3. Retrieve 3rd rank using iloc
print("\n3rd Rank:", marks.iloc[2])

# 4. Filter marks greater than 90
print("\nMarks greater than 90:")
print(marks[marks > 90])

1st Rank: 95

Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd Rank: 89

Marks greater than 90:
Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_2380/4153896813.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("1st Rank:", marks[0])


3. Manipulating Series:
● Modify the mark of the student with the 1st rank to 100.
● Remove the entry corresponding to the last rank from the Series.
● Compute the CGPA by dividing each mark in the Series by 10.

In [11]:
import pandas as pd

marks = pd.Series(
    [95, 88, 82, 76, 70],
    index=['1st Rank', '2nd Rank', '3rd Rank', '4th Rank', '5th Rank']
)

# Modify 1st rank mark
marks['1st Rank'] = 100

# Remove last rank
marks = marks.drop('5th Rank')

# Calculate CGPA
cgpa = marks / 10

print("Modified Marks:")
print(marks)

print("\nCGPA:")
print(cgpa)

Modified Marks:
1st Rank    100
2nd Rank     88
3rd Rank     82
4th Rank     76
dtype: int64

CGPA:
1st Rank    10.0
2nd Rank     8.8
3rd Rank     8.2
4th Rank     7.6
dtype: float64


Pandas DataFrame:

1. Creating Pandas DataFrame:
● Create a Pandas DataFrame named transactions with the following data:
➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'
➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [12]:
import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


2. Data Exploration:
● Display the transactions DataFrame and its basic information, including
head, tail, shape, column names, and data types.
● Display only the 'ProductCategory' and 'Amount' columns.
● Retrieve the last 3 columns of the DataFrame using iloc or loc.
● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
● Find the value counts for the 'ProductCategory' column.
● Find the unique values in the 'Region' column.
● Group by 'Region' and find the mean amount for each region.

In [13]:
# Display the DataFrame
print(transactions)

# Display the first 5 rows
print(transactions.head())

# Display the last 5 rows
print(transactions.tail())

# Display the shape of the DataFrame
print(transactions.shape)

# Display column names
print(transactions.columns)

# Display data types
print(transactions.dtypes)

# Display only ProductCategory and Amount columns
print(transactions[['ProductCategory', 'Amount']])

# Retrieve the last 3 columns using iloc
print(transactions.iloc[:, -3:])

# Filter rows where Region is North and Amount is greater than 200
print(transactions[(transactions['Region'] == 'North') &
                   (transactions['Amount'] > 200)])

# Find value counts for ProductCategory
print(transactions['ProductCategory'].value_counts())

# Find unique values in Region
print(transactions['Region'].unique())

# Group by Region and find mean Amount
print(transactions.groupby('Region')['Amount'].mean())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West 

3. Manipulating the DataFrame:
● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
● Add a new column 'Discount' by calculating 10% of the 'Amount'.
● Remove the row with TransactionID 109.
● Delete the 'Discount' column from the DataFrame.

In [14]:
# Modify Amount for TransactionID 102
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

# Add Discount column
transactions['Discount'] = transactions['Amount'] * 0.10

# Remove TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]

# Delete Discount column
transactions = transactions.drop('Discount', axis=1)

# Display the final DataFrame
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
